id: P6AB333A0
initial_creation_type: ocr
source_metadata:
  volumes:
    8bf05b349e22449e9c9f74440198b381:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: གནོད་པ་སེལ་བའི་བདུད་རྩི།
      total_pages: 1379
      volume_number: 37
